### ISSUE TITLE
Can't connect with mongoDB new auth method

### ISSUE THREAD

**Issue by afharo** [cayasso/mongo-oplog#11]
This module reports an error authenticating to MongoDB deployments using the new auth method.

It is usually solved updating the MongoDB client.

**Comment by cayasso** [comment]
@afharo can you provide more insight on this issue you are having, perhaps a failing test case if still the case, mongo-oplog@0.2.0 is out with latest mongodb driver

**Comment by afharo** [comment]
I've tried the new version and it is working now. Thank you so much.
Closing the issue...
