### ISSUE TITLE
Authentication against admin database fails for Mongo 3.0.4

### ISSUE THREAD

**Issue by jdarling** [cayasso/mongo-oplog#14]
If you have a connection string such as:
```
mongodb://myuser:mypass@localhost:27017/admin
```

And try to use mongo-oplog it will fail since it authenticates against the right database but then tries to use the oplog.rs database in the authenticated database.

Seems like the Connection (in connect.js) needs to call db.db('local') to get the local database and then perform the cursor on the oplog.rs collection.

Tried this, but that didn't completely seem to solve the issue :(  Will keep looking into it.

**Comment by jdarling** [comment]
The PR above fixes this issue.

**Comment by cayasso** [comment]
@jdarling Awesome!!! 
Can you add a test cases for this? and I will release version 0.2.2.

Thanks again!

**Comment by jdarling** [comment]
Well, I was going to LOL problem is if you add authentication on Mongo 3.0 it adds universally.  So then all the other test cases fail.

Only thing I could come up with was to run tests, turn on security, run tests, turn off security.  Unfortunately, for me at least, that isn't an option.

I did test it against my local encrypted and secured version.
