### ISSUE TITLE
does this lib use polling

### ISSUE THREAD

**Issue by the1mills** [cayasso/mongo-oplog#16]
Can you describe how this lib accomplishes listening to the oplog? Does it use polling or does it somehow hook into MongoDB?

**Comment by ORESoftware** [comment]
I was wondering the same thing - I was going to use the oplog in order to create a realtime server - I'd like to use this lib just want to make sure it wasn't polling MongoDB. I looked through the code and it doesn't seem like there is polling.

**Comment by cayasso** [comment]
@the1mills no polling, mongodb has Tailable Cursors that can remain open listening to document changes on capped collections, the oplog is a big capped collection for more info on this check this out http://docs.mongodb.org/manual/tutorial/create-tailable-cursor/ and here http://docs.mongodb.org/manual/core/replica-set-oplog/

**Comment by the1mills** [comment]
cool thanks. I will try it out. what I was thinking of doing was using the lib and then finding out which collection each oplog event happened on. I would take the name of the collection, go to Redis and find a list of users currently connected and interested in that collection and then send updates to each connected user.

From the front-page of the repo:

```javascript
oplog.on('insert', function (doc) {
  console.log(doc.op);
});

oplog.on('update', function (doc) {
  console.log(doc.op);
});

oplog.on('delete', function (doc) {
  console.log(doc.op._id);
});
```

I assume there is a way to get the name of the collection through the doc object?
