### ISSUE TITLE
Op.on invoked twice!

### ISSUE THREAD

**Issue by oreza** [cayasso/mongo-oplog#20]
op.on() gets called twice, even thought there is one message in oplog (db.oplog.rs)!

**Comment by cayasso** [comment]
Hi @oreza can you be more specific on your issue, what version of `mongo-oplog` are you using, and op.on() which event? all events? even better can you post some code that shows the issue?

**Comment by cayasso** [comment]
Closing do to no response

**Comment by oreza** [comment]
Sorry about that, your message got buried in tons of junk mail. We are using standard Docker image for mongo, setup for replication and we are using mongo-oplog@0.2.1. Code is pretty straight forward, it 
Setup looks like this:

// Setup Oplog cursor
var oplog = MongoOplog(process.env.MONGODB_OPLOG_URI, { ns: 'notifications.message' }).tail();
if (oplog) {
    console.log("Connected to mongo instance ", process.env.MONGODB_OPLOG_URI);
}

And Insert handler looks like this:

oplog.on('insert', function (data) {
    var username;
    var message = data.o;

    if (data.op !== 'i') {
        return;
    }
    // emit message to connected socket etc .....
}

This insert handler gets invoked twice! As a work around, we are currently filtering out the double messages.

**Comment by cayasso** [comment]
Hey @oreza Can you try using the latest version mongo-oplog@1.0.0-rc.1 and let me know if you still see the same issue?

Thanks!

**Comment by oreza** [comment]
Thank you for your response, I will let you know!

**Comment by kondapallipavan** [comment]
Even I am facing same issues  with mongo-oplog@1.0.0-rc.1

Here I am placing my log 
------------------------------------
2015-09-15 07:25:30.400  INFO  - Received realtime data ::::::::
 { ts: '6194639598832844801',
  h: '5489436227566672093',
  v: 2,
  op: 'u',
  ns: 'oculus.objects',
  o2: { _id: '5502f87ce4b084cced541841' },
  o:
   { _id: '5502f87ce4b084cced541841',
     _class: 'java.util.HashMap',
     tenantId: '-1234',
     sn: 'sn 2',
     appId: '1',
     accountTId: '5502f570e4b084cced54183f',
     scmaVer: '3.0',
     objCat: 'SENSORS',
     appFamily: [ [Object] ],
     uId: { 'mnf:mdl:sn': ':mdl 2:sn 2' },
     appName: 'DefaultApplication',
     objType: null,
     crtdDt: '2015-03-13T14:47:24.552Z',
     name: 'Sensor 2',
     userId: 'admin',
     uptdDt: '2015-03-13T14:47:24.552Z',
     lifeState: 'ACTV',
     ipAdrs: null,
     descr: null,
     mnf: null,
     mdl: 'mdl 2',
     test: 'test' } }

2015-09-15 07:25:33.205  INFO  - Received realtime data ::::::::
 { ts: '6194639598832844801',
  h: '5489436227566672093',
  v: 2,
  op: 'u',
  ns: 'oculus.objects',
  o2: { _id: '5502f87ce4b084cced541841' },
  o:
   { _id: '5502f87ce4b084cced541841',
     _class: 'java.util.HashMap',
     tenantId: '-1234',
     sn: 'sn 2',
     appId: '1',
     accountTId: '5502f570e4b084cced54183f',
     scmaVer: '3.0',
     objCat: 'SENSORS',
     appFamily: [ [Object] ],
     uId: { 'mnf:mdl:sn': ':mdl 2:sn 2' },
     appName: 'DefaultApplication',
     objType: null,
     crtdDt: '2015-03-13T14:47:24.552Z',
     name: 'Sensor 2',
     userId: 'admin',
     uptdDt: '2015-03-13T14:47:24.552Z',
     lifeState: 'ACTV',
     ipAdrs: null,
     descr: null,
     mnf: null,
     mdl: 'mdl 2',
     test: 'test' } }


My code:
-------------------------------
main.js 
----------------------

async = require("async");
var memwatch = require('memwatch');
ObjectID = require('mongodb').ObjectID;
var java = require("java");
var log4js = require('log4js');

memwatch.on('leak', function(info) {
 console.error('Leak info : ',info);
});
memwatch.on('stats', function(info) {
 console.error('Mem stats : ',info);
});
console.log('Node ENV : ',process.env.NODE_ENV)
var connectionManager = require("./connectionManager.js");
var config=require("./config.js");
var HashMap = java.import('java.util.HashMap');
var node_map = new HashMap();
var neo_ucount = 0;
var neo_icount = 0;
var count = 0;
var es_ucount = 0;
var es_icount = 0;
log4js.configure('./config/nodejs_log4j_configuration.json',{});
var real_log = log4js.getLogger("realtime");
var historical_log = log4js.getLogger("historical");
function process_data(data, op, stream,log) {
	var neo_op_type = null;
	var es_op_type = null;
	var neo_res = null
	var es_res = null;
	var op_type = null;
	async.parallel([
			function (callback) {

				connectionManager.getNeo4j(log,function (err, neo) {

							if(err)
							{
								log.error('Exception caught while connecting to neo4j',err);
							}
							else if(neo)
							{
									try {
										node_map = new HashMap();
										node_map.putSync("_id", data._id);
										node_map.putSync("accountTId", data.accountTId);
										node_map.putSync("appId", data.appId);
										node_map.putSync("crtdDt", data.crtdDt);
										node_map.putSync("uptdDt", data.uptdDt);
										node_map.putSync("lifeState", data.lifeState);
										node_map.putSync("objCat", data.objCat);
										node_map.putSync("objType", data.objType);
										log.info('Final data to insert/update for neo4j :::::::: ', '\n', node_map.toStringSync());
										if (op == 'createOculusNode') {
											neo_res = java.callMethodSync(neo, "createOculusNode", node_map);
											if (neo_res != null) {
												neo_icount++;
												neo_op_type = 'insert';
											}
										}

									} catch (ex) {
										try {
											var st = ex.cause.getMessageSync();
											log.warn('Failed to create node : ', st);
											if (st.indexOf('409:node already exists') > -1) {
												op = 'updateOculusNode'
											}
										} catch (ex) {
											neo_res = 'Neo4j Error : ' + ex.cause.getMessageSync();
											log.error('Neo4j Error : (',data._id,')', ex.cause.getMessageSync());
										}
									}
									try {
										if (op == 'updateOculusNode') {
											neo_res = java.callMethodSync(neo, "updateOculusNode", node_map);
											if (neo_res != null) {
												neo_op_type = 'update';
												neo_ucount++;
											}
										}

									} catch (ex) {
										try {
											var st = ex.cause.getMessageSync();
											log.warn('Failed to update node : ', st);
											if (st.indexOf('404:no object found for') > -1) {
												neo_res = java.callMethodSync(neo, "createOculusNode", node_map);
												if (neo_res != null) {
													neo_icount++;
													neo_op_type = 'insert';
												}
											}
										} catch (ex) {
											neo_res = 'Neo4j Error : ' + ex.cause.getMessageSync();
											log.error('Neo4j Error : (',data._id,')',ex.cause.getMessageSync());
										}

									}
								
							}
					
						
					callback();

				});

			},
			function (callback) {

				connectionManager.getES(log,function (err, es) {
					
					if(err)
					{
						log.error('Exception caught while connectiong to es',es)
					}else if (es)
					{
						if (data.appFamily) {
						var fmdata = {}
						data.appFamily.forEach(function (key) {
							var fsdata = {};
							key.afData.forEach(function (key1) {
								fsdata[key1.k] = key1.v
							});
							fmdata[key.afName] = fsdata
						});
						delete data.appFamily
						data.af = fmdata
					}
						log.info('Final data to insert/update in ES :::::::: ', '\n', data);
						var options = {
							index : 'objects',
							id : data._id,
							type : data.objCat.toLowerCase(),
							body:data
						};
						es.index(options,function (err, edata) {
							if (err)
							{
								es_res = err;
								log.error('ES Error : (',data._id,')', err);
							}
							else
								es_res = edata;
							if (edata)
								if (edata.created == true) {
									es_op_type = 'insert'
									es_icount++;
								} else if (edata.created == false) {
									es_op_type = 'update'
									es_ucount++;
								}
							callback();
						});
					}
					


				});

			}
		], function (err) {
		count++;
		if(neo_res)neo_res=neo_res.toStringSync()
		var fobj = {
			'count' : count,
			'neo4j' : {
				'action' : neo_op_type,
				'count' : {
					'insert' : neo_icount,
					'update' : neo_ucount,
				},
				'response' : neo_res
			},
			'es' : {
				'action' : es_op_type,
				'count' : {
					'insert' : es_icount,
					'update' : es_ucount,
				},
				'response' : es_res
			}
		}
		log.info('Final Response  :::::::::::::::::::::::::::::::::::::::: ', '\n', fobj);
		if (stream)
		{
			stream.resume();
		}

	});

}
function process_real_time_data(data, type) {

	data = JSON.parse(JSON.stringify(data));
	real_log.info('Received realtime data ::::::::', '\n', data);
	if (data.o.objCat == null) {
		sync_by_id(data.o2._id, 'updateOculusNode',real_log)

	} else if ((data.o.objCat == 'ACCOUNTS' || data.o.objCat == 'SENSORS') && (data.o.scmaVer == '3.0' || data.o.scmaVer == 'v3')) {
		process_data(data.o, type, null,real_log)

	} else {
		real_log.info('Ignored ' + data.o.objCat);
		return true;
	}

}

function process_sync_by_id_data() {
	historical_log.info('Start syncing by id ......');
	if (process.argv[3] == null) {
		historical_log.info('Mongodb id argument is missing.');
		process.exit(1);
	} else {
		sync_by_id(process.argv[3], 'createOculusNode',historical_log)
	}
}

function sync_data() {
	sync_all_data();
	real_time_sync();
}

function process_sync_by_date()
{
	historical_log.info('Start syncing data by date  ......');
	if (process.argv[3] == null) {
		sync_data_by_date(1);
		real_time_sync();
	} 
	else {	
	sync_data_by_date(process.argv[3]);
	real_time_sync();
	}
	
}

function sync_all_data() {
	historical_log.info('Start syncing all data......');
	connectionManager.getDb(historical_log,function (err, db) {
		if(err)
		{
			historical_log.error('Exception caught in sync_all_data',err)
		}else if(db)
		{
				var collection = db.collection('objects');	
				var stream = collection.find(config.mongo_db_filter).batchSize(1000).stream({
						transform : JSON.stringify
					});

				stream.on('end', function () {
					db.close();
				});
				stream.on('data', function (data) {
					stream.pause();
					data = JSON.parse(data);
					historical_log.info('Received stream data ::::::::', '\n', data);
					process_data(data, 'createOculusNode', stream,historical_log);

				});
		}
		
	});

}

function sync_data_by_date(noOfDays)
{
	connectionManager.getDb(historical_log,function (err, db) {
		if(err)
		{
			historical_log.error('Exception caught while getting connection',err)
		}else if(db)
		{
		var collection = db.collection('objects');
		var fiter_date=new Date((new Date()).getTime() - (noOfDays * 24 * 60 * 60 * 1000))
		var new_filter=config.mongo_db_filter;
		new_filter["$and"][2]={"uptdDt" :{$gte : fiter_date}}		
		var stream = collection.find(new_filter).batchSize(1000).stream({
						transform : JSON.stringify
					});
				stream.on('end', function () {
					db.close();
				});
				stream.on('data', function (data) {
					stream.pause();
					data = JSON.parse(data);
					historical_log.info('Received stream data ::::::::', '\n', data);
					process_data(data, 'createOculusNode', stream,historical_log);

				});
		}
		
	});
}

function real_time_sync() {

	real_log.info('Start realtime syncing ......');
	connectionManager.getOplog(real_log,function (err, oplog) {
		oplog.on('insert', function (data) {
			process_real_time_data(data, 'createOculusNode')
		});
		oplog.on('update', function (data) {

			process_real_time_data(data, 'updateOculusNode')
		});
		oplog.on('end', function () {
			real_log.info('Stream ended');
		});
		oplog.on('error', function (error) {
		  real_log.error('Mongo oplog Error',error);
		});
		oplog.stop(function () {
			real_log.info('server stopped');
		});
		oplog.tail(function () {
			real_log.info('tailing started');
		})
		oplog.on('op', function (data) {});

	});

}
function sync_by_id(id, type,log) {
	connectionManager.getDb(log,function (err, db) {
		if(err)
		{
			log.error('Exception caught in sync_by_id',err)
		}
		else if(db)
		{
			var collection = db.collection('objects');
			var obj_id = new ObjectID(id)
			var new_filter=config.mongo_db_filter_by_id;
			new_filter["$and"][2]["_id"]=obj_id
			collection.findOne(new_filter, {}, function (err, data) {
				if(data)
				{
					data = JSON.parse(JSON.stringify(data));
				    log.info('Retrived data for id (' + id + ' )::::::::', '\n', data);
					process_data(data, type, null,log)
				}
				else
				{
					log.info('Ignored', id)
				}		
			});
			
		}
	});

}
switch (process.argv[2]) {
case '1':
	sync_data();
	break;
case '2':
	sync_all_data();
	break;
case '3':
	real_time_sync();
	break;
case '4':
	process_sync_by_id_data();
	break;
case '5':
	process_sync_by_date();
	break;
default:
	console.log('| -Please give right argument-|');
	console.log('| --------------------------- |');
	console.log('| 1 -> Sync data ------------ |');
	console.log('| 2 -> Sync old data -------- |');
	console.log('| 3 -> Sync realtime data --- |');
	console.log('| 4 -> Sync by id  -----------|');
	console.log('| 5 -> Sync by date-----------|');
	console.log('| --------------------------- |');
}

----------------------------------------------
connectionManager.js
---------------------------------------------

var MongoClient = require('mongodb').MongoClient;
var MongoOplog = require('mongo-oplog');
var java = require("java");
var fs = require("fs");
var elasticsearch = require('elasticsearch');
var config=require("./config.js");
java.options.push('-Dlog4j.configuration=file:config/log4j.properties');
var dependencies = fs.readdirSync('lib');
dependencies.forEach(function (dependency) {
	java.classpath.push('lib/' + dependency);
})
var db_singleton = null;
var oplog = null;
var neo_util = null;
var es = null;

exports.getDb = function getDb(log,callback) {
	if (db_singleton&&db_singleton.serverConfig.isConnected()) {
		log.info('connection state:',db_singleton.serverConfig.isConnected());
		callback(null, db_singleton);
	} else {
		log.info("Creating new connection..");
		var connURL = 'mongodb://' + config.mongo_url;
		MongoClient.connect(connURL, config.mongo_db_conn_options,
		function (err, db) {
			if (err)
				log.info("Error creating new connection " , err);
			else {
				db_singleton = db;
				log.info("Created new connection");
			}
			callback(err, db_singleton);
			return;
		});
	}
}
exports.getOplog = function getOplog(log,callback) {
	if (oplog) {
		callback(null, oplog);
	} else {
		var connURL = 'mongodb://' + config.mongo_oplog_url
		var oplog = new MongoOplog(connURL, config.mongo_db_ns,config.mongo_db_conn_options).tail();
		callback(null, oplog);
	}
}

exports.getNeo4j = function getNeo4j(log,callback) {
	try {
		if (neo_util) {
			callback(null, neo_util)
		} else {
			var neo4j_url = 'http://' + config.neo4j_url;
			neo_util = java.newInstanceSync("com.trimble.oculus.core.resources.util.Neo4jUtil", neo4j_url, config.neo4j_username, config.neo4j_password);
			callback(null, neo_util);
		}

	} catch (ex) {
		callback(ex, null);
	}

}

exports.getES = function getES(log,callback) {
	try {
		if (es) {
			callback(null, es);
		} else {
			es = new elasticsearch.Client(config.es_config);
			callback(null, es);
		}
	} catch (ex) {
		callback(ex, null);
	}

}

--------------------------
config.js
--------------------------
var config = require('config-node')({
		dir : 'config',
		ext : null,
		env : process.env.NODE_ENV || 'development'
	});
module.exports = config;
 

Thanks
-Pavan

**Comment by kondapallipavan** [comment]
forget to give config json

--------------------
development.json 
--------------------

{
	"mongo_oplog_url" : "******:********@mongomaster/local?authSource=oculus",
	"mongo_url" : "********:*******@mongomaster/oculus",
	"neo4j_url" : "neo4j01:7474/db/data",
	"mongo_db_ns" : "oculus.objects",
	"neo4j_username" : "neo4j",
	"neo4j_password" : "oculus321$",
	"mongo_db_conn_options" : {
		"db" : {
			"retryMiliSeconds" : 2000,
			"numberOfRetries" : 100,
			"native_parser" : false
		},
		"server" : {
			"poolSize" : 10,
			"auto_reconnect" : true,
			"socketOptions" : {
				"keepAlive" : 1,
				"connectTimeoutMS" : 30000
			}

		},
		"replset" : {
			"socketOptions" : {
				"keepAlive" : 1,
				"connectTimeoutMS" : 30000
			},
			"rs_name" : "rs0",
			"connectWithNoPrimary" : true
		}
	},
	"es_config" : {
		  "host": "es01:9200",
		  "log": {
				"type": "file",
				"level": "info",
				"path": "./logs/elasticsearch.log"
				}
	},
	"mongo_db_filter" : {
		"$and" : [{
				"$or" : [{
						"objCat" : "ACCOUNTS"
					}, {
						"objCat" : "SENSORS"
					}
				]
			}, {
				"$or" : [{
						"scmaVer" : "3.0"
					}, {
						"scmaVer" : "v3"
					}
				]
			}
		]
	},
		"mongo_db_filter_by_id" : {
		"$and" : [{
				"$or" : [{
						"objCat" : "ACCOUNTS"
					}, {
						"objCat" : "SENSORS"
					}
				]
			}, {
				"$or" : [{
						"scmaVer" : "3.0"
					}, {
						"scmaVer" : "v3"
					}
				]
			},
			{"_id":"?"}
		]
	}
}

**Comment by kondapallipavan** [comment]
Hi even  i am facing same issues with  mongo-oplog@1.0.0-rc.1.

Here  i copied 
---------
my log 
----------------------
2015-09-15 07:25:30.400 INFO - Received realtime data ::::::::
{ ts: '6194639598832844801',
h: '5489436227566672093',
v: 2,
op: 'u',
ns: 'oculus.objects',
o2: { _id: '5502f87ce4b084cced541841' },
o:
{ _id: '5502f87ce4b084cced541841',
_class: 'java.util.HashMap',
tenantId: '-1234',
sn: 'sn 2',
appId: '1',
accountTId: '5502f570e4b084cced54183f',
scmaVer: '3.0',
objCat: 'SENSORS',
appFamily: [ [Object] ],
uId: { 'mnf:mdl:sn': ':mdl 2:sn 2' },
appName: 'DefaultApplication',
objType: null,
crtdDt: '2015-03-13T14:47:24.552Z',
name: 'Sensor 2',
userId: 'admin',
uptdDt: '2015-03-13T14:47:24.552Z',
lifeState: 'ACTV',
ipAdrs: null,
descr: null,
mnf: null,
mdl: 'mdl 2',
test: 'test' } }

2015-09-15 07:25:33.205 INFO - Received realtime data ::::::::
{ ts: '6194639598832844801',
h: '5489436227566672093',
v: 2,
op: 'u',
ns: 'oculus.objects',
o2: { _id: '5502f87ce4b084cced541841' },
o:
{ _id: '5502f87ce4b084cced541841',
_class: 'java.util.HashMap',
tenantId: '-1234',
sn: 'sn 2',
appId: '1',
accountTId: '5502f570e4b084cced54183f',
scmaVer: '3.0',
objCat: 'SENSORS',
appFamily: [ [Object] ],
uId: { 'mnf:mdl:sn': ':mdl 2:sn 2' },
appName: 'DefaultApplication',
objType: null,
crtdDt: '2015-03-13T14:47:24.552Z',
name: 'Sensor 2',
userId: 'admin',
uptdDt: '2015-03-13T14:47:24.552Z',
lifeState: 'ACTV',
ipAdrs: null,
descr: null,
mnf: null,
mdl: 'mdl 2',
test: 'test' } }

And also i am placing my code here

-------------
main.js
-------------
async = require("async");
var memwatch = require('memwatch');
ObjectID = require('mongodb').ObjectID;
var java = require("java");
var log4js = require('log4js');

memwatch.on('leak', function(info) {
 console.error('Leak info : ',info);
});
memwatch.on('stats', function(info) {
 console.error('Mem stats : ',info);
});
console.log('Node ENV : ',process.env.NODE_ENV)
var connectionManager = require("./connectionManager.js");
var config=require("./config.js");
var HashMap = java.import('java.util.HashMap');
var node_map = new HashMap();
var neo_ucount = 0;
var neo_icount = 0;
var count = 0;
var es_ucount = 0;
var es_icount = 0;
log4js.configure('./config/nodejs_log4j_configuration.json',{});
var real_log = log4js.getLogger("realtime");
var historical_log = log4js.getLogger("historical");
function process_data(data, op, stream,log) {
	var neo_op_type = null;
	var es_op_type = null;
	var neo_res = null
	var es_res = null;
	var op_type = null;
	async.parallel([
			function (callback) {

				connectionManager.getNeo4j(log,function (err, neo) {

							if(err)
							{
								log.error('Exception caught while connecting to neo4j',err);
							}
							else if(neo)
							{
									try {
										node_map = new HashMap();
										node_map.putSync("_id", data._id);
										node_map.putSync("accountTId", data.accountTId);
										node_map.putSync("appId", data.appId);
										node_map.putSync("crtdDt", data.crtdDt);
										node_map.putSync("uptdDt", data.uptdDt);
										node_map.putSync("lifeState", data.lifeState);
										node_map.putSync("objCat", data.objCat);
										node_map.putSync("objType", data.objType);
										log.info('Final data to insert/update for neo4j :::::::: ', '\n', node_map.toStringSync());
										if (op == 'createOculusNode') {
											neo_res = java.callMethodSync(neo, "createOculusNode", node_map);
											if (neo_res != null) {
												neo_icount++;
												neo_op_type = 'insert';
											}
										}

									} catch (ex) {
										try {
											var st = ex.cause.getMessageSync();
											log.warn('Failed to create node : ', st);
											if (st.indexOf('409:node already exists') > -1) {
												op = 'updateOculusNode'
											}
										} catch (ex) {
											neo_res = 'Neo4j Error : ' + ex.cause.getMessageSync();
											log.error('Neo4j Error : (',data._id,')', ex.cause.getMessageSync());
										}
									}
									try {
										if (op == 'updateOculusNode') {
											neo_res = java.callMethodSync(neo, "updateOculusNode", node_map);
											if (neo_res != null) {
												neo_op_type = 'update';
												neo_ucount++;
											}
										}

									} catch (ex) {
										try {
											var st = ex.cause.getMessageSync();
											log.warn('Failed to update node : ', st);
											if (st.indexOf('404:no object found for') > -1) {
												neo_res = java.callMethodSync(neo, "createOculusNode", node_map);
												if (neo_res != null) {
													neo_icount++;
													neo_op_type = 'insert';
												}
											}
										} catch (ex) {
											neo_res = 'Neo4j Error : ' + ex.cause.getMessageSync();
											log.error('Neo4j Error : (',data._id,')',ex.cause.getMessageSync());
										}

									}
								
							}
					
						
					callback();

				});

			},
			function (callback) {

				connectionManager.getES(log,function (err, es) {
					
					if(err)
					{
						log.error('Exception caught while connectiong to es',es)
					}else if (es)
					{
						if (data.appFamily) {
						var fmdata = {}
						data.appFamily.forEach(function (key) {
							var fsdata = {};
							key.afData.forEach(function (key1) {
								fsdata[key1.k] = key1.v
							});
							fmdata[key.afName] = fsdata
						});
						delete data.appFamily
						data.af = fmdata
					}
						log.info('Final data to insert/update in ES :::::::: ', '\n', data);
						var options = {
							index : 'objects',
							id : data._id,
							type : data.objCat.toLowerCase(),
							body:data
						};
						es.index(options,function (err, edata) {
							if (err)
							{
								es_res = err;
								log.error('ES Error : (',data._id,')', err);
							}
							else
								es_res = edata;
							if (edata)
								if (edata.created == true) {
									es_op_type = 'insert'
									es_icount++;
								} else if (edata.created == false) {
									es_op_type = 'update'
									es_ucount++;
								}
							callback();
						});
					}
					


				});

			}
		], function (err) {
		count++;
		if(neo_res)neo_res=neo_res.toStringSync()
		var fobj = {
			'count' : count,
			'neo4j' : {
				'action' : neo_op_type,
				'count' : {
					'insert' : neo_icount,
					'update' : neo_ucount,
				},
				'response' : neo_res
			},
			'es' : {
				'action' : es_op_type,
				'count' : {
					'insert' : es_icount,
					'update' : es_ucount,
				},
				'response' : es_res
			}
		}
		log.info('Final Response  :::::::::::::::::::::::::::::::::::::::: ', '\n', fobj);
		if (stream)
		{
			stream.resume();
		}

	});

}
function process_real_time_data(data, type) {

	data = JSON.parse(JSON.stringify(data));
	real_log.info('Received realtime data ::::::::', '\n', data);
	if (data.o.objCat == null) {
		sync_by_id(data.o2._id, 'updateOculusNode',real_log)

	} else if ((data.o.objCat == 'ACCOUNTS' || data.o.objCat == 'SENSORS') && (data.o.scmaVer == '3.0' || data.o.scmaVer == 'v3')) {
		process_data(data.o, type, null,real_log)

	} else {
		real_log.info('Ignored ' + data.o.objCat);
		return true;
	}

}

function process_sync_by_id_data() {
	historical_log.info('Start syncing by id ......');
	if (process.argv[3] == null) {
		historical_log.info('Mongodb id argument is missing.');
		process.exit(1);
	} else {
		sync_by_id(process.argv[3], 'createOculusNode',historical_log)
	}
}

function sync_data() {
	sync_all_data();
	real_time_sync();
}

function process_sync_by_date()
{
	historical_log.info('Start syncing data by date  ......');
	if (process.argv[3] == null) {
		sync_data_by_date(1);
		real_time_sync();
	} 
	else {	
	sync_data_by_date(process.argv[3]);
	real_time_sync();
	}
	
}

function sync_all_data() {
	historical_log.info('Start syncing all data......');
	connectionManager.getDb(historical_log,function (err, db) {
		if(err)
		{
			historical_log.error('Exception caught in sync_all_data',err)
		}else if(db)
		{
				var collection = db.collection('objects');	
				var stream = collection.find(config.mongo_db_filter).batchSize(1000).stream({
						transform : JSON.stringify
					});

				stream.on('end', function () {
					db.close();
				});
				stream.on('data', function (data) {
					stream.pause();
					data = JSON.parse(data);
					historical_log.info('Received stream data ::::::::', '\n', data);
					process_data(data, 'createOculusNode', stream,historical_log);

				});
		}
		
	});

}

function sync_data_by_date(noOfDays)
{
	connectionManager.getDb(historical_log,function (err, db) {
		if(err)
		{
			historical_log.error('Exception caught while getting connection',err)
		}else if(db)
		{
		var collection = db.collection('objects');
		var fiter_date=new Date((new Date()).getTime() - (noOfDays * 24 * 60 * 60 * 1000))
		var new_filter=config.mongo_db_filter;
		new_filter["$and"][2]={"uptdDt" :{$gte : fiter_date}}		
		var stream = collection.find(new_filter).batchSize(1000).stream({
						transform : JSON.stringify
					});
				stream.on('end', function () {
					db.close();
				});
				stream.on('data', function (data) {
					stream.pause();
					data = JSON.parse(data);
					historical_log.info('Received stream data ::::::::', '\n', data);
					process_data(data, 'createOculusNode', stream,historical_log);

				});
		}
		
	});
}

function real_time_sync() {

	real_log.info('Start realtime syncing ......');
	connectionManager.getOplog(real_log,function (err, oplog) {
		oplog.on('insert', function (data) {
			process_real_time_data(data, 'createOculusNode')
		});
		oplog.on('update', function (data) {

			process_real_time_data(data, 'updateOculusNode')
		});
		oplog.on('end', function () {
			real_log.info('Stream ended');
		});
		oplog.on('error', function (error) {
		  real_log.error('Mongo oplog Error',error);
		});
		oplog.stop(function () {
			real_log.info('server stopped');
		});
		oplog.tail(function () {
			real_log.info('tailing started');
		})
		oplog.on('op', function (data) {});

	});

}
function sync_by_id(id, type,log) {
	connectionManager.getDb(log,function (err, db) {
		if(err)
		{
			log.error('Exception caught in sync_by_id',err)
		}
		else if(db)
		{
			var collection = db.collection('objects');
			var obj_id = new ObjectID(id)
			var new_filter=config.mongo_db_filter_by_id;
			new_filter["$and"][2]["_id"]=obj_id
			collection.findOne(new_filter, {}, function (err, data) {
				if(data)
				{
					data = JSON.parse(JSON.stringify(data));
				    log.info('Retrived data for id (' + id + ' )::::::::', '\n', data);
					process_data(data, type, null,log)
				}
				else
				{
					log.info('Ignored', id)
				}		
			});
			
		}
	});

}
switch (process.argv[2]) {
case '1':
	sync_data();
	break;
case '2':
	sync_all_data();
	break;
case '3':
	real_time_sync();
	break;
case '4':
	process_sync_by_id_data();
	break;
case '5':
	process_sync_by_date();
	break;
default:
	console.log('| -Please give right argument-|');
	console.log('| --------------------------- |');
	console.log('| 1 -> Sync data ------------ |');
	console.log('| 2 -> Sync old data -------- |');
	console.log('| 3 -> Sync realtime data --- |');
	console.log('| 4 -> Sync by id  -----------|');
	console.log('| 5 -> Sync by date-----------|');
	console.log('| --------------------------- |');
}


---------------
connectionManager.js
---------------

var MongoClient = require('mongodb').MongoClient;
var MongoOplog = require('mongo-oplog');
var java = require("java");
var fs = require("fs");
var elasticsearch = require('elasticsearch');
var config=require("./config.js");
java.options.push('-Dlog4j.configuration=file:config/log4j.properties');
var dependencies = fs.readdirSync('lib');
dependencies.forEach(function (dependency) {
	java.classpath.push('lib/' + dependency);
})
var db_singleton = null;
var oplog = null;
var neo_util = null;
var es = null;

exports.getDb = function getDb(log,callback) {
	if (db_singleton&&db_singleton.serverConfig.isConnected()) {
		log.info('connection state:',db_singleton.serverConfig.isConnected());
		callback(null, db_singleton);
	} else {
		log.info("Creating new connection..");
		var connURL = 'mongodb://' + config.mongo_url;
		MongoClient.connect(connURL, config.mongo_db_conn_options,
		function (err, db) {
			if (err)
				log.info("Error creating new connection " , err);
			else {
				db_singleton = db;
				log.info("Created new connection");
			}
			callback(err, db_singleton);
			return;
		});
	}
}
exports.getOplog = function getOplog(log,callback) {
	if (oplog) {
		callback(null, oplog);
	} else {
		var connURL = 'mongodb://' + config.mongo_oplog_url
		var oplog = new MongoOplog(connURL, config.mongo_db_ns,config.mongo_db_conn_options).tail();
		callback(null, oplog);
	}
}

exports.getNeo4j = function getNeo4j(log,callback) {
	try {
		if (neo_util) {
			callback(null, neo_util)
		} else {
			var neo4j_url = 'http://' + config.neo4j_url;
			neo_util = java.newInstanceSync("com.trimble.oculus.core.resources.util.Neo4jUtil", neo4j_url, config.neo4j_username, config.neo4j_password);
			callback(null, neo_util);
		}

	} catch (ex) {
		callback(ex, null);
	}

}

exports.getES = function getES(log,callback) {
	try {
		if (es) {
			callback(null, es);
		} else {
			es = new elasticsearch.Client(config.es_config);
			callback(null, es);
		}
	} catch (ex) {
		callback(ex, null);
	}

}


------------------------
config.js
----------------------

var config = require('config-node')({
		dir : 'config',
		ext : null,
		env : process.env.NODE_ENV || 'development'
	});
module.exports = config;


------
config/development.json
-------

{
	"mongo_oplog_url" : "test:test@mongomaster/local?authSource=oculus",
	"mongo_url" : "test:test@mongomaster/oculus",
	"neo4j_url" : "neo4j01:7474/db/data",
	"mongo_db_ns" : "oculus.objects",
	"neo4j_username" : "test",
	"neo4j_password" : "test",
	"mongo_db_conn_options" : {
		"db" : {
			"retryMiliSeconds" : 2000,
			"numberOfRetries" : 100,
			"native_parser" : false
		},
		"server" : {
			"poolSize" : 10,
			"auto_reconnect" : true,
			"socketOptions" : {
				"keepAlive" : 1,
				"connectTimeoutMS" : 30000
			}

		},
		"replset" : {
			"socketOptions" : {
				"keepAlive" : 1,
				"connectTimeoutMS" : 30000
			},
			"rs_name" : "rs0",
			"connectWithNoPrimary" : true
		}
	},
	"es_config" : {
		  "host": "es01:9200",
		  "log": {
				"type": "file",
				"level": "info",
				"path": "./logs/elasticsearch.log"
				}
	},
	"mongo_db_filter" : {
		"$and" : [{
				"$or" : [{
						"objCat" : "ACCOUNTS"
					}, {
						"objCat" : "SENSORS"
					}
				]
			}, {
				"$or" : [{
						"scmaVer" : "3.0"
					}, {
						"scmaVer" : "v3"
					}
				]
			}
		]
	},
		"mongo_db_filter_by_id" : {
		"$and" : [{
				"$or" : [{
						"objCat" : "ACCOUNTS"
					}, {
						"objCat" : "SENSORS"
					}
				]
			}, {
				"$or" : [{
						"scmaVer" : "3.0"
					}, {
						"scmaVer" : "v3"
					}
				]
			},
			{"_id":"?"}
		]
	}
}


Thanks
-Pavan
