### ISSUE TITLE
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

### ISSUE THREAD

**Issue by kleysonr** [cayasso/mongo-oplog#23]
Yesterday trying to use mongo-oplog version 1.0.0, I was getting the following error:

**{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version**

To fix I've changed:
**bson = require('../build/Release/bson')**
to
**bson = require('../browser_build/bson')**

in the **node_modules/mongo-oplog/node_modules/mongo-oplog-cursor/node_modules/bson/ext/index.js** file.

System: Ubuntu 12.04

**Comment by cayasso** [comment]
@kleysonr I removed the dependency of `bson.Timestamp` and replaced it with `bson-timestamp` in `mongo-oplog-cursor` module this should remove completely this build error.

Thanks for reporting!
