### ISSUE TITLE
Add oplog.on('open', [fn])

### ISSUE THREAD

**Issue by kleysonr** [cayasso/mongo-oplog#24]
As a developer, I would like to use mongo-oplog with Javascript Promise.

So, it's necessary a point to return a 'resolve()' when the mongodb connection is estabilished.

Then, is it possible add a **oplog.on('open', [fn])** option ?

**Comment by cayasso** [comment]
@kleysonr Great idea!, I did some annotations to your PR, after those changes I will merge ;-)

**Comment by cayasso** [comment]
I explained the reason I am closing this in the pull request.
