### ISSUE TITLE
"not authorized for query on local.oplog.rs"

### ISSUE THREAD

**Issue by ORESoftware** [cayasso/mongo-oplog#26]
I got this error for the first time today in an attempt to connect to a MongoDB cluster on a Compose deployment:

![image](https://cloud.githubusercontent.com/assets/11139560/10683693/8596cd44-78f9-11e5-9b98-6e9b8cd22780.png)

the original code looking like:

```javascript
var url = 'mongodb://abc:xyz@candidate.54.mongolayer.com:10050/app42153482';

console.log('about to tail...');
var oplog = new MongoOplog(url).tail(function (err, oplogStream) {
    if (err) {
        console.error(err);
    }
    else {
        console.log('tail event:', oplogStream);
    }
});
```

I did a Google but nothing obvious appears to me, know about this one?

**Comment by Necromos** [comment]
Error message is clearly saying that you lack access to oplog. 
Check out how to do this: https://docs.compose.io/common-questions/getting-oplog-access.html
