### ISSUE TITLE
Does work? Nothing output.

### ISSUE THREAD

**Issue by itlodge** [cayasso/mongo-oplog#30]
Hi, I try to use this module, and write some testing code below:

    var MongoOplog = require('mongo-oplog');
    var oplog = MongoOplog('mongodb://127.0.0.1:27017/local',
      {ns: 'test_sails.question'}).tail();
    console.log(oplog);
    oplog.on('update', function (doc) {
      console.log(doc);
    });
    oplog.on('error', function (error) {
      console.log(error);
    });

And I run this code, then do an update operation of collection "question". But nothing happen. Do I doing something wrong? Thanks.

**Comment by cayasso** [comment]
@itlodge Did you setup your Mongo with Replica Set as mentioned at the end of the README?

**Comment by itlodge** [comment]
@cayasso , Yes, I set my Mongo with Replica Set,   and I can see the oplog in a mongo shell.

**Comment by cayasso** [comment]
Please try cloning the project and running the test suite.

On Wednesday, March 16, 2016, Yuanhang Zheng <notifications@github.com>
wrote:

> @cayasso <https://github.com/cayasso> , Yes, I set my Mongo with Replica
> Set, and I can see the oplog in a mongo shell.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cayasso/mongo-oplog/issues/30#issuecomment-197665119>
>


-- 
J.B.

**Comment by itlodge** [comment]
@cayasso , if I run only one mongod instance with option "master", can this module work?

**Comment by itlodge** [comment]
Now it works after I set it with Replica Set. Thanks for your help!
