### ISSUE TITLE
Cannot connect to database "local" when need username and password

### ISSUE THREAD

**Issue by itlodge** [cayasso/mongo-oplog#32]
Hi, 
    I test this module in production mongodb with username and password. However, I [cannot create users on the local database](https://docs.mongodb.org/manual/reference/method/db.createUser/#local-database). How can I connect to database "local" and monitor oplog?

**Comment by itlodge** [comment]
Finally I solved this problem.
First, create a user in admin for database 'local'.
```javascript
  use admin;
  db.createUser({'user': 'xxx', 'pwd': 'xxx',
      'roles': [{role: 'read', db: 'local'}]});
```
Then, let mongo-oplog connect to 'admin' but use database 'local'.
```javascript
      let url = 'mongodb://';
      if (config.local_user && config.local_password) {
        url += config.local_user + ':' + config.local_password + '@';
      }
      url += config.host + ':' + config.port + '/admin'; 
      const options = {ns: config.database + '.' + table + '$',
          databse: 'local'};
      const oplog = MongoOplog(url, options).tail();
```
Hope can help someone.

**Comment by Gilwyad** [comment]
databse is not a valid option and database is not supported any more on 2.0.2
