### ISSUE TITLE
what is the ns:'test.posts' means?

### ISSUE THREAD

**Issue by Muffasa** [cayasso/mongo-oplog#33]
can somone please explain me what is the ns connnectionString option? I could not find it on the mongo docs.
I have en issue where the events wont fire, and it think it has someting to do with it.
I tried to change it to my db name and collection:
`var oplog = MongoOplog('mongodb://127.0.0.1:27017/local', { ns: 'db_prod.feeds' }).tail();`
without any success.

**Comment by itlodge** [comment]
@Muffasa , yes,  "test" is the database and "posts" is the collection.

**Comment by WolfieWerewolf** [comment]
This is a very good question and probably should be in the actual documentation on the front page.
