### ISSUE TITLE
Does it store positon of last oplog record read?

### ISSUE THREAD

**Issue by ShipraShalini** [cayasso/mongo-oplog#34]
I am using mongo-oplog to tail mongo-oplog.
In current state, if my application is down, it misses all the changes during the down time.

I would like to know if there's a mechanism to store the postion of last read oplog record or any method to achieve this?

**Comment by itlodge** [comment]
+1 for this requirement.

**Comment by toszter** [comment]
What are the downsides/upsides of storing the last op in an unindexed capped table that's 1 document deep to achieve this independently of `mongo-oplog` sources?

**Comment by mpseay** [comment]
We store a "since" value in redis for this purpose. On the start of our app we grab the since value to determine the last message received. But.. recently ran into a problem with that as there is no index on the oplog so searching to a specific time has a pretty negative impact on the database.

**Comment by cayasso** [comment]
As @mpseay mentioned oplog in MongoDB doesn't support indexes there is nothing much to do or to add here. 

https://docs.mongodb.com/manual/core/tailable-cursors/

In the mean time I will close this but you can always reopen if there are any clever idea for this or issue related to the current implementation.

**Comment by cayasso** [comment]
BTW mongo-oplog@2.0.0 is out :)

**Comment by tony-kerz** [comment]
hi @cayasso sorry i'm new here, does the 2.0.0 version do anything around this feature request?

i was just reading [this blog post](http://www.askasya.com/post/bestversion/) which shows filtering by "previous timestamp" like:

```
var cursor=db.getSiblingDB("local").getCollection("oplog.rs"
    ).find({"ns":namespace,"ts":{"$gte":prevTS}}
    ).addOption(DBQuery.Option.oplogReplay
    ).addOption(DBQuery.Option.awaitData
    ).addOption(DBQuery.Option.tailable
    ).addOption(DBQuery.Option.noTimeout);
```

so something like this would incur "table scan" like performance hit?
is there anyway for a client of your lib to specify a filter as above if they are prepared for that hit?

honestly, i'm an oplog tailing (and in fact tailable-cursor) noob, so apologies in advance for stupid questions.

**Comment by cayasso** [comment]
hi @tony-kerz

> so something like this would incur "table scan" like performance hit?

Yes because `ts` doesn't have an index in the oplog collection. This is our default behavior without the extra `lastApplied` collection [L26](https://github.com/cayasso/mongo-oplog/blob/master/src/stream.js#L26)

> is there anyway for a client of your lib to specify a filter as above if they are prepared for that hit?

As @mpseay you can pass [`since`](https://github.com/cayasso/mongo-oplog/blob/master/src/index.js#L39) when creating your `mongo-oplog` instance. I will document this in the next release.

**Comment by tony-kerz** [comment]
thanks @cayasso, i see the `since` option [here](https://github.com/cayasso/mongo-oplog/blob/master/src/index.js#L36).

pragmatically tho, if the goal is to process __all__ events and the "subscriber" missed some because of down-time, isn't searching by `since` the only option?

**Comment by mattfysh** [comment]
just found this option, although I did accidentally use the deserialized timestamp format for a while. Finally realised I need to grab the timestamp high value. thanks @cayasso for making this - very awesome library :)

**Comment by kdekooter** [comment]
@cayasso where can we find the documentation of `since`? specially interested in what format is expected.
