### ISSUE TITLE
mongo-oplog setup

### ISSUE THREAD

**Issue by interfaith** [cayasso/mongo-oplog#37]
how must mongodb be used ?

i get 'oplog.$main'  via ExecStart=/usr/bin/mongod  --master -f /etc/mongod.conf

some 'other' oplog is needed via some other mongodb start command ??

**Comment by cayasso** [comment]
This might help https://github.com/cayasso/mongo-oplog#run-tests

**Comment by interfaith** [comment]
this.cn = options.coll || 'oplog.rs';

can this be changed to oplog.$main ?

**Comment by cayasso** [comment]
@interfaith you can always pass a different collection name using `options.coll`
```js
MongoOplog('mongodb://127.0.0.1:27017/local', { coll: 'whatever' })
```

But you need to set up the replica set, have you tried `ExecStart=/usr/bin/mongod  --replSet test -f /etc/mongod.conf`?

**Comment by interfaith** [comment]
yes that is what we are doing now.
the ubuntu daemon fails to start

[Service]
User=mongodb
Group=mongodb
ExecStart=/usr/bin/mongod   -f /etc/mongod.conf
changing this fails

and in mongod.conf
setting up the mongo 3.2 variables for replSet also
fails

so ? why not avoid replSet and use --master ?

On Tue, May 31, 2016 at 9:55 AM, Jonathan Brumley <notifications@github.com>
wrote:

> @interfaith <https://github.com/interfaith> you can always pass a
> different collection name using options.coll
>
> MongoOplog('mongodb://127.0.0.1:27017/local', { coll: 'whatever' })
>
> But you need to set up the replica set, have you tried ExecStart=/usr/bin/mongod
> --replSet test -f /etc/mongod.conf?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cayasso/mongo-oplog/issues/37#issuecomment-222750928>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAs5z-lAlYkJEk83rtQRHaExqSwhu_qXks5qHGgGgaJpZM4Il2O0>
> .
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
replication:
   oplogSizeMB: 200
   replSetName: test

this fails in mongod.conf for 3.2

only launching via command line works ? not as a service

On Tue, May 31, 2016 at 10:05 AM, Mark Spowage <spowage@gmail.com> wrote:

> yes that is what we are doing now.
> the ubuntu daemon fails to start
>
> [Service]
> User=mongodb
> Group=mongodb
> ExecStart=/usr/bin/mongod   -f /etc/mongod.conf
> changing this fails
>
> and in mongod.conf
> setting up the mongo 3.2 variables for replSet also
> fails
>
> so ? why not avoid replSet and use --master ?
>
> On Tue, May 31, 2016 at 9:55 AM, Jonathan Brumley <
> notifications@github.com> wrote:
>
>> @interfaith <https://github.com/interfaith> you can always pass a
>> different collection name using options.coll
>>
>> MongoOplog('mongodb://127.0.0.1:27017/local', { coll: 'whatever' })
>>
>> But you need to set up the replica set, have you tried ExecStart=/usr/bin/mongod
>> --replSet test -f /etc/mongod.conf?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/cayasso/mongo-oplog/issues/37#issuecomment-222750928>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAs5z-lAlYkJEk83rtQRHaExqSwhu_qXks5qHGgGgaJpZM4Il2O0>
>> .
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
this worked
https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04

**Comment by interfaith** [comment]
sudo systemctl unmask mongodb
