### ISSUE TITLE
How to listen to two collections with one oplog

### ISSUE THREAD

**Issue by jbockerstette** [cayasso/mongo-oplog#38]
I want to monitor two collections. My collections are Apple.rpps and Apple.dps. If I want to monitor one collection I would do this:

`oplog = MongoOplog('mongodb://127.0.0.1:27017/local', {ns: 'Apple.rpps'}).tail();`

How can I change this statement to monitor both collections?

**Comment by cayasso** [comment]
@jbockerstette you can do:
```js
oplog = MongoOplog('mongodb://127.0.0.1:27017/local', {ns: 'Apple.*ps'}).tail();
```
