### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by AndreSteenveld** [cayasso/mongo-oplog#47]
I have a project where I use mongo-oplog as a dependency, during the startup of the application babel-polyfill is imported. When importing monog-oplog the error "only one instance of babel-polyfill is allowed" is thrown from babel-polyfill.

I've encountered a similar issue before and the found that replacing `import 'babel-polyfill'` with `global._babelPolyfill || require( "babel-polyfill" );` sort of works around the problem but doesn't really solve it because the assumption is made that every library will make sure to check their babel-polyfill import.

**Comment by aslafy-z** [comment]
I made a fork ([aestetype/mongo-oplog](https://github.com/aestetype/mongo-oplog/)) who includes @AndreSteenveld's patch. It's published on npm through `@aestetype/mongo-oplog`.

**Comment by cayasso** [comment]
This commit https://github.com/cayasso/mongo-oplog/commit/fc2a1ec671b3cfd07f08009ccc10eb3b7e35841d should address this issue.

**Comment by aslafy-z** [comment]
@cayasso Could you please npm deploy the fix ?

**Comment by cayasso** [comment]
I was doing it while you were writing ;-)
2.1.0 is out now
