### ISSUE TITLE
Need documentation for configuration with node app !!! 

### ISSUE THREAD

**Issue by hiteshsomani** [cayasso/mongo-oplog#55]

**Comment by cayasso** [comment]
There is already some reference in the [README](https://github.com/cayasso/mongo-oplog#run-tests) but it seems not to be clear, I think because it is in the Run test section, I will update with clear steps.

**Comment by cayasso** [comment]
Here you go https://github.com/cayasso/mongo-oplog/commit/fd9703c8be4fea5d7e0b968b35365c0908312c5e
