### ISSUE TITLE
regular expression denial of service vulnerability

### ISSUE THREAD

**Issue by zvictor** [cayasso/mongo-oplog#56]
I couldn't find anyone reporting this yet, which is weird to me, so here it goes:

This package fails the [NSP check](https://www.npmjs.com/package/nsp) because `nsp < 2.6.9` is vulnerable to regular expression denial of service.

&nbsp; | Regular Expression Denial of Service                              
---------- | -----------
Name | debug
CVSS | 3.7 (Low)
Installed | 2.3.3
Vulnerable | <= 2.6.8 || >= 3.0.0 <= 3.0.1
Patched | >= 2.6.9 < 3.0.0 || >= 3.1.0
Path | mongo-oplog@2.0.2 > debug@2.3.3
More Info | https://nodesecurity.io/advisories/534

the `debug` package needs to be updated to at least version `2.6.9`.

**Comment by cayasso** [comment]
@zvictor Thanks for reporting this, the issue is that old version of `debug` module, I will update and push a new release.

**Comment by cayasso** [comment]
Fixed [here](https://github.com/cayasso/mongo-oplog/commit/45ad3531935f1455d76a8e9a7ca28881fd68f1e5) and will soon be out in new release.

**Comment by zvictor** [comment]
thank you so much for the quick reply :)
