### ISSUE TITLE
With MongoDB 1.x oplog tail start takes quite a long time – 2.x is faster

### ISSUE THREAD

**Issue by pakastin** [cayasso/mongo-oplog#6]
You should update to MongoDB 2.x – it's way faster! Just to let you know..

**Comment by cayasso** [comment]
@pakastin checkout 1.0.x which adds MongoDB 2 & 3 support https://github.com/cayasso/mongo-oplog/tree/develop

**Comment by cayasso** [comment]
mongo-oplog@0.2.0 is out with latest mongodb driver
