### ISSUE TITLE
QUESTION: Multiple `ns`

### ISSUE THREAD

**Issue by pbr0ck3r** [cayasso/mongo-oplog#64]
Is there a way to have multiple DB and tables in one statement?

I am trying the following...
`mongoOplog('mongodb://127.0.0.1:27017/local', {ns: 'test.users', ns: 'test.roles', ns:'test.companies'})`

I get events (insert, delete, update) to fire on`companies` but for some reason `roles, users` will not fire.

Is there another way I should be monitoring multiple tables in the database?

**Comment by vinespring** [comment]
@pbr0ck3r Looks like it builds a `$regex` query for the `ns` field. ([stream.js](https://github.com/cayasso/mongo-oplog/blob/master/src/stream.js#L25))

You should be able to do `ns: 'test.roles|test.companies|test.users'`.

**Comment by pbr0ck3r** [comment]
@vinespring... that does indeed work! Thanks so much!

**Comment by cayasso** [comment]
Closing since solution was pointed out.
