### ISSUE TITLE
typescript types aren't working

### ISSUE THREAD

**Issue by ORESoftware** [cayasso/mongo-oplog#65]
I installed:
` 
"mongo-oplog": "^2.1.0",
`

and then I have 

```js
import MongoOplog from 'mongo-oplog'
```

I am seeing

<img width="1185" alt="screenshot 2018-03-15 23 25 57" src="https://user-images.githubusercontent.com/11139560/37506676-3b4fecc8-28a8-11e8-8a3f-6154cc801ff4.png">

Do you know why the types aren't being recognized? I see an index.d.ts file in this project. So I shouldn't have to use `@types/mongo-oplog` (which doesn't exist anyway).

**Comment by ORESoftware** [comment]
I did some sleuthing because I am cool like that and I see this:

<img width="305" alt="screenshot 2018-03-15 23 27 47" src="https://user-images.githubusercontent.com/11139560/37506754-85645484-28a8-11e8-9c8f-6e0be14228ed.png">

The index.d.ts file is not being moved from src to lib. Instead of transpiled from src to lib, maybe consider just putting all the files in lib (.ts, .d.ts, .js).  I have seen things done both ways, frankly keeping them all in one places is fine.

**Comment by Boxie5** [comment]
I guess this maybe is because `src` folder is set to be ignored [here in .npmignore](https://github.com/cayasso/mongo-oplog/blob/master/.npmignore#L5)

> node_modules
> examples
> npm-debug.log
> dump.rdb
> src/

thus, the [types](https://github.com/cayasso/mongo-oplog/blob/master/package.json#L6) info set in `package.json` is useless

>  "types": "./src/index.d.ts"

**Comment by cayasso** [comment]
This should be fixed in 2.1.4
