### ISSUE TITLE
Oplog filters without a wildcard character unexpectedly match namespaces as if they *had* a wildcard character

### ISSUE THREAD

**Issue by ColmHally** [cayasso/mongo-oplog#9]
If I have a mongo-oplog tailer and I use a filter for a namespace such as `testDb.test`, when I insert documents into the `testDb.testCol` collection, I see the inserts via the `MongoOplog.on()` function as expected.

However, if I then insert something into a similar-but-different collection, e.g. a collection named `testDb.test.unrelated`, I still see the inserts in the above `.on()` handler.

# Demonstration:
This code to setup:
```javascript
var MongoOplog = require('mongo-oplog');
var oplog = MongoOplog('mongodb://127.0.0.1:27017/local', 'testDb', {}).tail();

oplog.filter('testDb.test').on('insert', function (doc) {
  console.info('Oplog: got doc for %s at %s', doc.ns, doc.ts.toString(), doc);
});
```

Then, begin inserting documents into the `testDb.test` collection via a MongoDB shell and you'll see them printed to the screen as expected.

Try, inserting into the `testDb.test.unrelated` and you will see those documents printed too! 

```
Oplog: got doc for testDb.test at 6128341457154605057 { ts: { _bsontype: 'Timestamp', low_: 1, high_: 1426865686 },
  h: { _bsontype: 'Long', low_: -584176087, high_: 2102653918 },
  v: 2,
  op: 'i',
  ns: 'testDb.test',
  o: { _id: 550c3e16552900c43e670edf, a: 'a' } }
Oplog: got doc for testDb.test.unrelated at 6128341525874081793 { ts: { _bsontype: 'Timestamp', low_: 1, high_: 1426865702 },
  h: { _bsontype: 'Long', low_: 414944956, high_: -417162172 },
  v: 2,
  op: 'i',
  ns: 'testDb.test.unrelated',
  o: { _id: 550c3e26552900c43e670ee0, a: 'a' } }
```

Correct me if I'm wrong, but since I didn't use a wildcard character in the string passed to  `.filter()`, then I should only expect exact namespace matches here, right?

**Comment by ColmHally** [comment]
Hey @cayasso, looks like this issue has been fixed by the guys maintaining the `wildcard` module:
https://github.com/DamonOehlman/wildcard/issues/5

Could you update the `wildcard` module to 1.1.1?

**Comment by cayasso** [comment]
@ColmHally thanks for been proactive :)

**Comment by ColmHally** [comment]
No problem, thanks for pulling in the fix!
